services:
  db:
    image: postgres:15
    container_name: guess-game-postgres
    environment:
      POSTGRES_USER: gguser
      POSTGRES_PASSWORD: ggpass
      POSTGRES_DB: guessdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: guess-game-redis
    ports:
      - "6379:6379"
    # Если хотим сохранять данные в volume:
    volumes:
      - redis_data:/data

  guess-game:
    build: .
    container_name: guess-game
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=gguser
      - DB_PASS=ggpass
      - DB_NAME=guessdb
      - REDIS_HOST=redis:6379
    depends_on:
      - db
      - redis

  migrations:
    # Используем тег, который точно есть на Docker Hub
    image: "migrate/migrate:v4.15.1"
    container_name: guess-game-migrations
    depends_on:
      - db
    volumes:
      - ./db/migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://gguser:ggpass@db:5432/guessdb?sslmode=disable",
      "up"
    ]

volumes:
  postgres_data:
  redis_data:
